export enum DoctorSpecialty {
    CARDIOLOGY = "CARDIOLOGIA",
    OPHTHALMOLOGY = "OFTALMOLOGIA",
    OTOLARYNGOLOGY = "OTORRINOLARINGOLOGIA",
    UROLOGY = "UROLOGIA",
    PEDIATRICS = "PEDIATRIA",
    NEUROLOGY = "NEUROLOGIA",
    NEPHROLOGY = "NEFROLOGIA"
}