export enum AppointmentStatusEnum {
    REQUESTED = "SOLICITADA",
    REJECTED = "RECHAZADA",
    SCHEDULED = "AGENDADA",
    ACCEPTED = "ACEPTADA",
    CANCELED = "CANCELADA",
    COMPLETED = "COMPLETADA",
    INICIATED = "INICIADA"
}