name: Deploy

on:
  push:
    branches:
      - master
  

jobs:
  test: 
      uses: ./.github/workflows/test.yml
  
  build:
    name: Deploy app to Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Heroku deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'myonlinedoctor-main'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
