name: Test

on:
  push:
  pull_request:
    branches: 
      - main
  workflow_call:    

jobs:
  
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm ci

    - name: Testing! 
      run: npm test